### ISSUE TITLE
[Bug]Error: Cannot find module './node_modules/react-scripts/config/webpack.config.dev' with react-script v2.1.2

### ISSUE THREAD

**Issue by kopax** [sharegate/craco#61]
## Cannot find webpack config with `react-scripts` **`2.1.2`**

I have updated my `react-scripts` dependencies from `2.1.1` to `2.1.2` and got the following error on both `npm start` and `npm run build`:

```sh
Error: Cannot find module /node_modules/react-scripts/config/webpack.config.dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at resolveConfigFilePath (/node_modules/@craco/craco/lib/cra.js:7:20)
    at getWebpackDevConfigPath (/node_modules/@craco/craco/lib/cra.js:25:12)
    at loadWebpackDevConfig (/node_modules/@craco/craco/lib/cra.js:29:22)
    at Object.<anonymous> (/node_modules/@craco/craco/scripts/start.js:18:26)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
```

### Expect

to start or build my unjected create-react-app.

### Result

Can't find the configuration `react-scripts/config/webpack.config.dev`

Seems obvious: https://github.com/facebook/create-react-app/tree/v2.1.2/packages/react-scripts/config

### Version

- Craco: 3.2.3

**Comment by ClaudiuCeia** [comment]
The way CRA organizes webpack configs seems to have changed with this commit: https://github.com/facebook/create-react-app/commit/30ee52cf3b2cbb6ac70999c02b1196bcaba8d4ca#diff-ee7ca784a2ec9d96668503d6394bdd62

**Comment by tzarger** [comment]
+1

**Comment by zhnoah** [comment]
+1

**Comment by hckhanh** [comment]
+1 👎

**Comment by ri7nz** [comment]
+1

**Comment by neodon** [comment]
Referencing the issue that introduced this problem: https://github.com/facebook/create-react-app/pull/5722

**Comment by Gamezpedia** [comment]
+1

**Comment by nanxiaobei** [comment]
Still not upgraded

**Comment by tangdw** [comment]
windows -> Error: Cannot find module 'E:\react-start\node_modules\react-scripts/config/webpack.config.dev'

**Comment by kopax** [comment]
Why did you switch ? Isn't this already fixed with #6 ?

**Comment by tzarger** [comment]
@kopax What does [#6](https://github.com/sharegate/craco/pull/6) have to do with this issue?

**Comment by kopax** [comment]
Seems like `react-app-rewired` is now release for `react-scripts` **2.1.2**, should I close this?

**Comment by abenhamdine** [comment]
> Seems like react-app-rewired is now release for react-scripts 2.1.2, should I close this?

No, why should you ? This project is not based on react-app-rewired and this issue is still there.

**Comment by ZKHelloworld** [comment]
+1

**Comment by nanxiaobei** [comment]
Where is @patricklafrance? 😑

**Comment by kopax** [comment]
Don't know. Did/may someone release the #62 under a scoped name?

**Comment by ltfschoen** [comment]
> Where is @patricklafrance? 😑

in Montréal according to his GH profile marker

**Comment by tahamshahzad** [comment]
https://medium.com/@tahamshahzad/get-ant-design-import-on-demand-working-with-create-react-app-v2-using-rescripts-cc822f98f7e5

I wrote this fix and it's working perfectly have a look

**Comment by panjiesw** [comment]
While I understand the need for you to move for `react-app-rewired`, I think this issue should've kept opened until the fix is landed. It helps the maintainer and others to keep track, and be aware that this is still an issue in `craco`.

**Comment by Delphier** [comment]
plz don't close.

**Comment by SergeyVolynkin** [comment]
_"Giving up"_ – is not a good reputation for the https://sharegate.com/ team.

I think current users of `craco` will be much happier if you just:
- [ ] Merge @hckhanh's PR to fix the bug
- [ ] Assign new maintainer for this project from the community.

cc @kopax @patricklafrance

**Comment by abenhamdine** [comment]
FWIW, I opened https://github.com/sharegate/craco/issues/67 to keep this issue visible for the maintainer and future readers

**Comment by ltfschoen** [comment]
what a joke

**Comment by ltfschoen** [comment]
so will we be continuing to close and re-open this issue multiple times just to encourage others to create multiple duplicates of the same issue to spam the maintainers?

**Comment by patricklafrance** [comment]
Hi,

Sorry for the delay, I add an accident and couldn't use a computer for a few weeks.

I'll make sure https://github.com/sharegate/craco/pull/62 is merged and release soon.
